version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "3080:3080"
    container_name: server
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true

  admin:
    build:
      context: ./admin
    ports:
      - "3030:3030"
    container_name: admin
    stdin_open: true
    volumes:
      - ./admin:/usr/src/app/admin
      - /usr/src/app/admin/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
