version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3080:3080"
    container_name: server
    volumes:
      - ./server:/usr/src/app/server
      - ./common:/usr/src/app/common
      - /usr/src/app/server/node_modules

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    depends_on: [server]
    container_name: client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
      - ./common:/usr/src/app/common
      - /usr/src/app/client/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true

  admin:
    build:
      context: ./
      dockerfile: ./admin/Dockerfile
    ports:
      - "3030:3000"
    depends_on: [server]
    container_name: admin
    stdin_open: true
    volumes:
      - ./admin:/usr/src/app/admin
      - ./common:/usr/src/app/common
      - /usr/src/app/admin/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
